name: BUILD
on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
      - 'release/[0-9]*.[0-9]*.x'
      - 'release/[0-9]*.x.x'
      - 'hotfix/[0-9]*.[0-9]*.[0-9]*'
jobs:
  upcoming_version:
    runs-on: ubuntu-latest
    container: tartar4s/semver-ci
    outputs:
      UPCOMING_VERSION: ${{ steps.set_upcoming_version.outputs.UPCOMING_VERSION }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - run: git config --global --add safe.directory .
      - name: Set upcoming version
        id: set_upcoming_version
        run: |
          if [[ $GITHUB_REF == refs/heads/release/[0-9]*.x.x ]]; then
            export SCOPE=major
          elif [[ $GITHUB_REF == refs/heads/develop || $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/release/[0-9]*.[0-9]*.x ]]; then
            export SCOPE=minor
          elif [[ $GITHUB_REF == refs/heads/hotfix/* ]]; then
            export SCOPE=patch
          else
            echo "Unsupported branch for versioning"
            exit 1
          fi
          echo "UPCOMING_VERSION=$(svci version)" >> "$GITHUB_OUTPUT"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: upcoming_version
    steps:
      - env:
          RELEASE_TAG: ${{needs.upcoming_version.outputs.UPCOMING_VERSION}}
        run: echo "$RELEASE_TAG"
