name: BUILD
on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
jobs:
  upcoming_version:
    runs-on: ubuntu-latest
    container: tartar4s/semver-ci:v0.4.0-rc.1
    outputs:
      UPCOMING_VERSION: ${{ steps.set_upcoming_version.outputs.UPCOMING_VERSION }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - run: git config --global --add safe.directory .
      - name: Set upcoming version
        id: set_upcoming_version
        #export MAJOR='^release/[0-9]+.x.x$'
        #export MINOR='^(develop|feature/.*|release/[0-9]+.[0-9]+.x)$'
        #export PATCH='^hotfix/[0-9]+.[0-9]+.[0-9]+$'
        run: |
          export SCOPE=$(svci scope $$GITHUB_REF_NAME)
          echo "UPCOMING_VERSION=$(svci version)" >> "$GITHUB_OUTPUT"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: upcoming_version
    steps:
      - env:
          RELEASE_TAG: ${{needs.upcoming_version.outputs.UPCOMING_VERSION}}
        run: echo "$RELEASE_TAG"
