name: BUILD
on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
jobs:
  upcoming_version:
    runs-on: ubuntu-latest
    container: tartar4s/semver-ci:v0.5.0-dev.185a31bc
    outputs:
      UPCOMING_VERSION: ${{ steps.set_upcoming_version.outputs.UPCOMING_VERSION }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Set upcoming version
        id: set_upcoming_version
        run: |
          git config --global --add safe.directory .
          export SCOPE=$(svci scope)
          echo "UPCOMING_VERSION=$(svci version)" >> "$GITHUB_OUTPUT"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: upcoming_version
    steps:
      - run: echo "$RELEASE_TAG"
    env:
      RELEASE_TAG: ${{needs.upcoming_version.outputs.UPCOMING_VERSION}}
  tag:
    runs-on: ubuntu-latest
    container: tartar4s/semver-ci:v0.5.0-dev.185a31bc
    needs: [upcoming_version, build]
    permissions:
      contents: write
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Tag
        run: |
          git config --global --add safe.directory .
          svci tag "$TAG_NAME"
    env:
      TAG_NAME: ${{needs.upcoming_version.outputs.UPCOMING_VERSION}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
