name: CI
on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
      - 'release/[0-9]*.[0-9]*.x'
jobs:
  checkout_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: checkout_repo
          path: ${{ github.workspace }}
  upcoming_version_minor:
    needs: checkout_repo
    runs-on: ubuntu-latest
    container:
      image: tartar4s/semver-ci:v0.3.0-rc.1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: checkout_repo
      - run: chown -R $(whoami):$(whoami) .
      - run: pwd && ls -al
      - name: Print upcoming version
        run: svci version
