name: CI
on:
  push:
    branches:
      - 'release/[0-9]*.x.x'
jobs:
  upcoming_version_minor:
    runs-on: ubuntu-latest
    container:
      image: tartar4s/semver-ci:v0.3.0-rc.1
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Print upcoming version
        run: svci version --scope major
