name: CI
on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
      - 'release/[0-9]*.[0-9]*.x'
jobs:
  upcoming_version_minor:
    runs-on: ubuntu-latest
    container: tartar4s/semver-ci:v0.3.0-rc.2
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - run: git config --global --add safe.directory *
      - name: Print upcoming version
        run: svci version
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
