name: CI
on:
  push:
    branches:
      - 'hotfix/[0-9]*.[0-9]*.[0-9]*'
jobs:
  upcoming_version_minor:
    runs-on: ubuntu-latest
    container:
      image: tartar4s/semver-ci:v0.3.0-rc.1
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Print upcoming version
        run: svci version --scope patch
