name: UPCOMING_VERSION
on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
      - 'release/[0-9]*.[0-9]*.x'
      - 'release/[0-9]*.x.x'
      - 'hotfix/[0-9]*.[0-9]*.[0-9]*'
jobs:
  upcoming_version:
    runs-on: ubuntu-latest
    container: tartar4s/semver-ci:v0.3.0
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - run: git config --global --add safe.directory .
      - name: Print upcoming version
        run: |
          if [[ $GITHUB_REF == refs/heads/release/[0-9]*.x.x ]]; then
            svci version --scope major
          elif [[ $GITHUB_REF == refs/heads/develop || $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/release/[0-9]*.[0-9]*.x ]]; then
            svci version
          elif [[ $GITHUB_REF == refs/heads/hotfix/* ]]; then
            svci version --scope patch
          else
            echo "Unsupported branch for versioning"
            exit 1
          fi
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
